name: .NET 8 NativeAOT CLI Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [win-x64]

    env:
      Solution_Name: p3dv5kg.sln           # Replace with your actual solution name
      Project_Path: p3dv5kg.csproj           # Replace with your actual project path

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore $env:Solution_Name

    - name: Restore (Runtime-specific)
      run: dotnet restore $env:Project_Path --runtime ${{ matrix.arch }}

    - name: Build
      run: dotnet build $env:Solution_Name --configuration Release --no-restore

    - name: Publish NativeAOT (${{ matrix.arch }})
      run: >
        dotnet publish $env:Project_Path
        --configuration Release
        --runtime ${{ matrix.arch }}
        /p:PublishAot=true
        --self-contained true
        --output ./publish/${{ matrix.arch }}
        --no-build
    - name: Upload Published NativeAOT (${{ matrix.arch }})
      uses: actions/upload-artifact@v4
      with:
        name: nativeaot-${{ matrix.arch }}
        path: ./publish/${{ matrix.arch }}
