name: .NET 8 NativeAOT CLI Publish
permissions:
  actions: write
  attestations: write
  checks: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [win-x64]
    env:
      Solution_Name: p3dkg.sln           # Replace with your actual solution name
      Project_Path: p3dkg.csproj           # Replace with your actual project path

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore $env:Solution_Name

    - name: Restore (Runtime-specific)
      run: dotnet restore $env:Project_Path --runtime ${{ matrix.arch }}

    - name: Build
      run: dotnet build $env:Solution_Name --configuration Release --no-restore

    - name: Publish NativeAOT (${{ matrix.arch }})
      run: >
        dotnet publish $env:Project_Path
        --configuration Release
        --runtime ${{ matrix.arch }}
        /p:PublishAot=true
        --self-contained true
        --output ./publish/${{ matrix.arch }}
        --no-build

    - name: Upload Release Asset (Windows Executable)
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./publish/${{ matrix.arch }}/p3dkg.exe
        asset_name: p3dkg.exe
        asset_content_type: application/octet-stream
